[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4"
awc = "3.7.0"
dotenv = "0.15.0"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.27"
tokio = {version = "1.45.0", features = ["full"]}
