services:
  app:
    image: a08-proxy
    build:
      context: .
    environment:
      - PORT=5000
      - MEWING_MENU_URL=${MEWING_MENU_URL}
      - OHIO_ORDER_URL=${OHIO_ORDER_URL}
      - SIGMA_AUTH_URL=${SIGMA_AUTH_URL}
    ports:
      - "5000:5000"